# -*- coding: utf-8 -*-
"""Aula19/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BqNe60KByVHJ4rRHPlS_pvPa5IO5Ow-0

# **Aula 6 - WHILE**

## Atividade 1

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

while True:
  nota = float(input('Digite uma nota entre 0 e 10: '))
  if nota > 0 and nota < 10:
    break
  print('Valor Inválido.\n')

"""## Atividade 2

2. Faça um programa que calcule o mostre a média aritmética de N notas.
"""

contador = 0
soma = 0
n = int(input('Digite a quantidade de notas a serem usadas para calcular a média: '))

while contador < n:
  nota = float(input(f'Digite a nota {contador + 1}: '))
  soma += nota
  contador += 1

media = soma / n

print(f'Média das notas: {media}')

"""## Atividade 3

3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.
"""

while True:
  usuario = input('Digite o nome do usuário: ')
  senha = input('Digite a senha: ')

  if usuario != senha:
    break
  print('O usuário e senha devem ser diferentes!\n')

print('\nUsuário registrado!')

"""## Atividade 4

4. Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00 Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

ano = 1995
salario = float(input('Digite seu salário base em 1995: R$ '))
percentual = 0.015

while ano < 2024:
  salario *= 1 + percentual
  percentual *= 2
  ano += 1
  print(f'Salário em {ano}: R$ {salario: .2f}')

"""## Atividade 5

5. Faça um programa que leia e valide as seguintes informações:
- Nome: maior que 3 caracteres;
- Idade: entre 0 e 150;
- Salário: maior que zero;
- Sexo: 'f' ou 'm';
- Estado Civil: 's', 'c', 'v', 'd';
"""

sexos = ('f','m')
estados_civis = ('s','c','v','d')

while True:
  nome = input('Digite seu nome: ')
  idade = int(input('Digite sua idade: '))
  salario = float(input('Digite seu salário: '))
  sexo = input('Digite seu sexo ("F" ou "M"): ').lower()
  estado_civil = input('Digite seu estado civil ("S", "C", "V" ou "D"): ').lower()

  if len(nome) >= 3 and idade > 0 and idade < 150 and salario > 0 and sexo in sexos and estado_civil in estados_civis:
    break

  print('Informações inválidas!\n')

"""## Atividade 6

6. Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

populacao_A = 80000
taxa_A = 1.03

populacao_B = 200000
taxa_B = 1.015

anos = 0

while populacao_A < populacao_B:
  # print(f'População A: {populacao_A: .2f}\nPopulação B: {populacao_B: .2f}\n')
  populacao_A *= taxa_A
  populacao_B *= taxa_B
  anos += 1

print(f'Anos necessários para que a população A ultrapasse B: {anos}')

"""## Atividade 7

7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

num = int(input('Digite um número para calcular seu fatorial: '))
fatorial = 1 if num > 0 else 0

while num > 0:
  fatorial *= num
  num -= 1

print(fatorial)

"""## Atividade 8

8. Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

soma = 0
quantidade = 0

print('Para encerrar o progama e realizar a média digite 0.\n')
while True:
  numero = float(input('Digite números:'))
  if numero == 0:
    break
  soma += numero
  quantidade += 1

if quantidade == 0:
  print('Não foram inseridos números no programa!')
else:
  media = soma / quantidade
  print(f'\nMédia dos números digitados: {media: .2f}')

"""## Atividade 9

9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
programa capaz de gerar a série até o n−ésimo termo.
"""

sequencia = []
contador = 0
termo = 0
n = int(input('Digite o termo para finalizar a sequência Fibonacci: '))

while contador < n:
  if contador < 2:
    sequencia.append(1)
    contador += 1
    continue
  termo = sequencia[-2] + sequencia[-1]
  sequencia.append(termo)
  print(termo)
  contador += 1

print(sequencia)

sequencia = [1,1]
termo = 0
n = int(input('Digite o termo para finalizar a sequência Fibonacci: '))

while True:
  termo = sequencia[-2] + sequencia[-1]
  if termo > n:
    break
  sequencia.append(termo)
  print(termo)

print(sequencia)

"""## Atividade 10

10. O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
- O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.

- O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
- A saída deve ser conforme o exemplo abaixo:
- Lojas Tabajara
- Produto 1: R 2.20
- Produto 2: R 5.80
- Produto 3: R 0
- Total: R 9.00
- Dinheiro: R 20.00
- Troco: R 11.00
"""

opcoes = ('s', 'n')

print('Loja Tabajara\n')
while True:
  total = 0
  num_produto = 1

  while True:
    produto = float(input(f'Produto {num_produto}: R$ '))
    if produto == 0:
      break
    num_produto += 1
    total += produto

  print(f'\nTotal: R$ {total}')

  dinheiro = float(input('Dinheiro: R$ '))
  troco = dinheiro - total

  if troco >= 0:
    print(f'Troco: R$ {troco: .2f}')
  else:
    print('Saldo insuficiente! Compra cancelada.')

  while True:
    opcao = input('Deseja continuar comprando?(S/N): ').lower()
    if opcao in opcoes:
      break
    print('Opção inválida! Digite novamente.\n')

  if opcao == 'n':
    break

"""## Atividade 11

11. O cardápio de uma lanchonete é o seguinte:

Especificação Código Preço

- Cachorro Quente 100 R 1,20
- Bauru Simples 101 R 1,30
- Bauru com ovo 102 R 1,50
- Hambúrguer 103 R 1,20
- Cheeseburguer 104 R 1,30
- Refrigerante 105 R 1,00

Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

codigos = (0,100,101,102,103,104,105)

cachorro_quente = { 'valor': 1.2, 'qtd': 0 }
bauru_simples = { 'valor': 1.3, 'qtd': 0 }
bauru_ovo = { 'valor': 1.5, 'qtd': 0 }
hamburguer = { 'valor': 1.2, 'qtd': 0 }
cheeseburguer = { 'valor': 1.3, 'qtd': 0 }
refrigerante = { 'valor': 1, 'qtd': 0 }

valor_total = 0

print('''
         Produto          Codigo      Preço
         ------------------------------------
         Cachorro Quente    100       R$ 1.20
         Bauru Simples      101       R$ 1.30
         Bauru com Ovo      102       R$ 1.50
         Hamburguer         103       R$ 1.20
         Chesseburguer      104       R$ 1.30
         Refrigerante       105       R$ 1.00

         Digite 0 em código para encerrar o pedido.
         ''')

while True:
  codigo = int(input('Digite o código do item a ser pedido: '))

  if codigo in codigos:
    if codigo == 0:
      break
    quantidade = int(input('Digite a quantidade desejada deste item: '))

    if codigo == 100:
      cachorro_quente['qtd'] += quantidade
      valor_total += cachorro_quente['valor'] * quantidade
    if codigo == 101:
      bauru_simples['qtd'] += quantidade
      valor_total += bauru_simples['valor'] * quantidade
    if codigo == 102:
      bauru_ovo['qtd'] += quantidade
      valor_total += bauru_ovo['valor'] * quantidade
    if codigo == 103:
      hamburguer['qtd'] += quantidade
      valor_total += hamburguer['valor'] * quantidade
    if codigo == 104:
      cheeseburguer['qtd'] += quantidade
      valor_total += cheeseburguer['valor'] * quantidade
    if codigo == 105:
      refrigerante['qtd'] += quantidade
      valor_total += refrigerante['valor'] * quantidade
  else:
    print('\nCódigo inválido! Insira novamente.')

print(f'\nCachorro quente: {cachorro_quente["qtd"]}x R$ {(cachorro_quente["qtd"] * cachorro_quente["valor"]): .2f}')
print(f'Bauru Simples: {bauru_simples["qtd"]}x R$ {(bauru_simples["qtd"] * bauru_simples["valor"]): .2f}')
print(f'Bauru com ovo: {bauru_ovo["qtd"]}x R$ {(bauru_ovo["qtd"] * bauru_ovo["valor"]): .2f}')
print(f'Hambúrguer: {hamburguer["qtd"]}x R$ {(hamburguer["qtd"] * hamburguer["valor"]): .2f}')
print(f'Cheeseburguer: {cheeseburguer["qtd"]}x R$ {(cheeseburguer["qtd"] * cheeseburguer["valor"]): .2f}')
print(f'Refrigerante: {refrigerante["qtd"]}x R$ {(refrigerante["qtd"] * refrigerante["valor"]): .2f}')
print(f'\nTotal do pedido: R$ {valor_total: .2f}')

"""## Atividade 12

12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados
por meio de código.
Os códigos utilizados são:
- 1, 2, 3, 4 - Votos para os respectivos candidatos
- (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
- 5 - Voto Nulo
- 6 - Voto em Branco

Faça um programa que calcule e mostre:

- O total de votos para cada candidato;
- O total de votos nulos;
- O total de votos em branco;
- A percentagem de votos nulos sobre o total de votos;
- A percentagem de votos em branco sobre o total de votos.

Para finalizar o conjunto de votos tem-se o valor zero.
"""

opcoes = ('s', 'n')
votos_validos = ('1','2','3','4','5','6','0')
votos_candidatos = {
    'Candidato 1': 0,
    'Candidato 2': 0,
    'Candidato 3': 0,
    'Candidato 4': 0,
    'Votos Nulos': 0,
    'Votos em Branco': 0,
}

total_votos = 0

print('Eleição Presidencial\n\n1 - Candidato 1\n2 - Candidato 2\n3 - Candidato 3\n4 - Candidato 4\n5 - Voto Nulo\n6 - Voto em Branco\n0 - Encerrar Votação\n')

while True:
  voto = input('Digite seu voto: ')
  if voto in votos_validos:
    if voto == '0':
      break
    if voto == '1':
      votos_candidatos['Candidato 1'] += 1
    if voto == '2':
      votos_candidatos['Candidato 2'] += 1
    if voto == '3':
      votos_candidatos['Candidato 3'] += 1
    if voto == '4':
      votos_candidatos['Candidato 4'] += 1
    if voto == '5':
      votos_candidatos['Votos Nulos'] += 1
    if voto == '6':
      votos_candidatos['Votos em Branco'] += 1
    total_votos += 1
  else:
    print('Voto inválido! Desconsiderando voto.\n')

percentual_nulo = (votos_candidatos['Votos Nulos'] * 100) / total_votos if total_votos != 0 else 0
percentual_branco = (votos_candidatos['Votos em Branco'] * 100) / total_votos if total_votos != 0 else 0

print('\nResultado: \n')
for voto, quantidade in votos_candidatos.items():
  print(f'{voto}: {quantidade}')

print(f'\nPercentual de votos nulos: {percentual_nulo: .2f}%')
print(f'Percentual de votos em branco: {percentual_branco: .2f}%')