# -*- coding: utf-8 -*-
"""Aula23/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_Y72GnJ3kkAhWMGx1O7y9YIcU2mwd7U
"""

T = int(input('Entre com número inteiro maior que 1: '))

#FOR
print('For: ', end=' ')
for t in range(T):
  print(f'{T-t}', end=' ')
print('\n')

#WHILE
print('While:', end=' ')
i = 0
while i < T:
  print(f'{T-i}', end=' ')
  i += 1

T = int(input('Entre com número inteiro maior que 1: '))
mult = -1
fat = 1
#FOR
print('For: ', end=' ')
for t in range(T):
  num = fat * (T-t)
  fat *= mult
  print(num, end=' ')
print('\n')

#WHILE
mult = -1
fat = 1
i = 0

print('While:', end=' ')
while i < T:
  num = fat * (T-i)
  fat *= mult
  print(num, end=' ')
  i += 1

N = int(input('Digite um número inteiro: '))

# FOR
print('For: ')
for i in range(1,N):
  print(f'{i**2}', end= ' ')
print('\n')

#WHILE
i = 1
print('While: ')
while i < N:
  print(f'{i**2}', end=' ')
  i += 1

palavra = input('Digite uma palavra que palíndromo: ').strip().lower()
reversa = ''
contador = 1

for i in range(len(palavra)-1, -1, -1):
  reversa += palavra[i]

if palavra == reversa:
  print('Essa palavra é um palíndromo.')
else:
  print('É mentira a palavra não é um palíndromo.')

N = int(input('Digite um número inteiro e positivo: '))

# Parte de cima do quadrado
print(' ', end='')
for i in range(N):
  print('-', end='')
print()

# Parte do meio do quadrado
for i in range(N):
  print(f'{"|"}{" "*N}{"|"}\n', end='')

# Parte de baixo do quadrado
print(' ', end='')
for i in range(N):
  print('-', end='')

N = int(input('Digite um número inteiro e positivo: '))

print(' ', end='')
print('-'*N)
print(f'{"|"}{" "*N}{"|"}\n'*N, end='')
print(' ', end='')
print('-'*N)

N = int(input('Digite um número inteiro e positivo: '))

for i in range(1,N+1):
  print('+'*i)